apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen_ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: epic_driscoll
        image: rahulmark42/generative_modeling:latest
        ports:
        - containerPort: 80
